#!/usr/bin/env ruby

# http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen

git_bundles = %w(
  godlygeek/tabular
  msanders/snipmate.vim
  scrooloose/nerdtree
  scrooloose/nerdcommenter
  scrooloose/snipmate-snippets
  timcharper/textile.vim
  tpope/vim-cucumber
  tpope/vim-haml
  tpope/vim-markdown
  tpope/vim-rails
  tpope/vim-repeat
  tpope/vim-surround
  tpope/vim-vividchalk
  Raimondi/delimitMate
  vim-ruby/vim-ruby
  kana/vim-textobj-user
  nelstrom/vim-textobj-rubyblock
  mileszs/ack.vim
  nathanaelkane/vim-indent-guides
  theIV/twerth-colors
  altercation/vim-colors-solarized
  mattn/gist-vim
  ervandew/supertab
  majutsushi/tagbar
  Lokaltog/vim-powerline
  sickill/vim-pasta
  vim-scripts/L9
  vim-scripts/minibufexpl.vim
  vim-scripts/jQuery
  vim-scripts/ActionScript
  vim-scripts/JSON.vim
  jc00ke/vim-tomdoc
)

exclude_bundles = [
  'vim-colors-olauzon',
  'processing'
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each { |d| FileUtils.rm_rf(d) unless exclude_bundles.include?(d) }

git_bundles.each do |bundle|
  dir = bundle.split('/').last.downcase
  puts "→ Unpacking #{bundle} into #{dir}"
  `hub clone #{bundle} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end
