#!/usr/bin/env ruby
# encoding: utf-8

# http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen

require 'fileutils'
require 'open-uri'
require 'yaml'

bundles = YAML.load(File.read('./vim/bundle_list.yml'))['github_bundles']
exclude_bundles = [ 'vim-colors-olauzon',
                    'processing',
                    'vim-smyck']

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each { |d|
  FileUtils.rm_rf(d) unless exclude_bundles.include?(d)
}

bundles.each do |bundle|
  dir = bundle.split('/').last.downcase
  puts "→ Unpacking #{bundle} into #{dir}"
  `hub clone #{bundle} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end
