#!/usr/bin/env ruby
# encoding: utf-8

# http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen

git_bundles = %w(
  godlygeek/tabular
  scrooloose/nerdtree
  scrooloose/nerdcommenter
  tpope/vim-cucumber
  tpope/vim-haml
  tpope/vim-markdown
  tpope/vim-rails
  tpope/vim-surround
  tpope/vim-vividchalk
  Raimondi/delimitMate
  vim-ruby/vim-ruby
  kana/vim-textobj-user
  nelstrom/vim-textobj-rubyblock
  mileszs/ack.vim
  theIV/twerth-colors
  altercation/vim-colors-solarized
  ervandew/supertab
  majutsushi/tagbar
  sickill/vim-pasta
  vim-scripts/L9
  vim-scripts/jQuery
  vim-scripts/ActionScript
  vim-scripts/JSON.vim
  theIV/vim-tomdoc
  kchmck/vim-coffee-script
  kien/ctrlp.vim
  myusuf3/numbers.vim
  Lokaltog/vim-easymotion
  othree/html5.vim
  slim-template/vim-slim
  vim-scripts/scratch.vim
  vim-scripts/css_color.vim
  skammer/vim-css-color
  hail2u/vim-css3-syntax
)

exclude_bundles = [
  'vim-colors-olauzon',
  'processing'
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each { |d| FileUtils.rm_rf(d) unless exclude_bundles.include?(d) }

git_bundles.each do |bundle|
  dir = bundle.split('/').last.downcase
  puts "→ Unpacking #{bundle} into #{dir}"
  `hub clone #{bundle} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end
